# Generated by SQL Server Management Studio at 21:13 on 31.12.2018

Import-Module SqlServer
# Set up connection and database SMO objects

$sqlConnectionString = "Data Source=WL-GZX0D32;Initial Catalog=FakeMobileCarrierDb;Integrated Security=True;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;Packet Size=4096;Application Name=`"Microsoft SQL Server Management Studio`""
$smoDatabase = Get-SqlDatabase -ConnectionString $sqlConnectionString

# If your encryption changes involve keys in Azure Key Vault, uncomment one of the lines below in order to authenticate:
#   * Prompt for a username and password:
#Add-SqlAzureAuthenticationContext -Interactive

#   * Enter a Client ID, Secret, and Tenant ID:
#Add-SqlAzureAuthenticationContext -ClientID '<Client ID>' -Secret '<Secret>' -Tenant '<Tenant ID>'

# Change encryption schema

$encryptionChanges = @()

# Add changes for table [dbo].[Users]
$encryptionChanges += New-SqlColumnEncryptionSettings -ColumnName dbo.Users.PhoneNumber -EncryptionType Deterministic -EncryptionKey "CEK_dbo_Users_PhoneNumber"

Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase

